### ISSUE TITLE
This plugin does not compile on Zeek 7.0

### ISSUE THREAD

**Issue by ghost** [corelight/zeek-community-id#28]
````
[ 28%] Building CXX object CMakeFiles/Corelight_CommunityID.dir/communityid.bif.cc.o
/zeek-community-id/src/communityid.bif:14:5: error: 'EVP_MD_CTX' does not name a type
   14 |     EVP_MD_CTX *ctx;
      |     ^~~~~~~~~~
/zeek-community-id/src/communityid.bif: In function 'void digest_init(Ctx*)':
/zeek-community-id/src/communityid.bif:18:10: error: 'struct Ctx' has no member named 'ctx'; did you mean 'Ctx'?
   18 |     ctx->ctx = ZEEK_DETAIL_NS::hash_init(ZEEK_DETAIL_NS::Hash_SHA1);
      |          ^~~
      |          Ctx
/zeek-community-id/src/communityid.bif: In function 'void digest_update(Ctx*, const void*, long unsigned int)':
/zeek-community-id/src/communityid.bif:22:38: error: 'struct Ctx' has no member named 'ctx'; did you mean 'Ctx'?
   22 |     ZEEK_DETAIL_NS::hash_update(ctx->ctx, data, len);
      |                                      ^~~
      |                                      Ctx
/zeek-community-id/src/communityid.bif: In function 'void digest_final(Ctx*, u_char*)':
/zeek-community-id/src/communityid.bif:26:37: error: 'struct Ctx' has no member named 'ctx'; did you mean 'Ctx'?
   26 |     ZEEK_DETAIL_NS::hash_final(ctx->ctx, md);
      |                                     ^~~
      |                                     Ctx
/zeek-community-id/src/communityid.bif:27:10: error: 'struct Ctx' has no member named 'ctx'; did you mean 'Ctx'?
   27 |     ctx->ctx = 0;
      |          ^~~
      |          Ctx
/zeek-community-id/src/communityid.bif: In function 'zeek::ValPtr zeek::BifFunc::CommunityID::hash_conn_bif(zeek::detail::Frame*, const zeek::Args*)':
/zeek-community-id/src/communityid.bif:152:19: error: 'SHA_DIGEST_LENGTH' was not declared in this scope; did you mean 'ZEEK_SHA_DIGEST_LENGTH'?
  152 |     u_char digest[SHA_DIGEST_LENGTH];
      |                   ^~~~~~~~~~~~~~~~~
      |                   ZEEK_SHA_DIGEST_LENGTH
/zeek-community-id/src/communityid.bif:165:24: error: 'digest' was not declared in this scope; did you mean 'sigset'?
  165 |     digest_final(&ctx, digest);
      |                        ^~~~~~
      |                        sigset
make[2]: *** [CMakeFiles/Corelight_CommunityID.dir/build.make:95: CMakeFiles/Corelight_CommunityID.dir/communityid.bif.cc.o] Error 1
make[2]: Leaving directory '/zeek-community-id/build'
make[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/Corelight_CommunityID.dir/all] Error 2
make[1]: Leaving directory '/zeek-community-id/build'
make: *** [Makefile:156: all] Error 2
make: Leaving directory '/zeek-community-id/build'
````
Is this plugin still maintained and if so is an update in the making?

Regards

Martin

**Comment by ghost** [comment]
Sorry just now read the readme stating that it is no longer needed from zeek 6 onwards
